use sta546;DROP TABLE IF EXISTS fullTable;CREATE TABLE fullTable(trackID INT NOT NULL ,
max_chroma_cens_01 DOUBLE DEFAULT NULL ,
max_chroma_cens_02 DOUBLE DEFAULT NULL ,
max_chroma_cens_03 DOUBLE DEFAULT NULL ,
max_chroma_cens_04 DOUBLE DEFAULT NULL ,
max_chroma_cens_05 DOUBLE DEFAULT NULL ,
max_chroma_cens_06 DOUBLE DEFAULT NULL ,
max_chroma_cens_07 DOUBLE DEFAULT NULL ,
max_chroma_cens_08 DOUBLE DEFAULT NULL ,
max_chroma_cens_09 DOUBLE DEFAULT NULL ,
max_chroma_cens_10 DOUBLE DEFAULT NULL ,
max_chroma_cens_11 DOUBLE DEFAULT NULL ,
max_chroma_cens_12 DOUBLE DEFAULT NULL ,
mean_chroma_cens_01 DOUBLE DEFAULT NULL ,
mean_chroma_cens_02 DOUBLE DEFAULT NULL ,
mean_chroma_cens_03 DOUBLE DEFAULT NULL ,
mean_chroma_cens_04 DOUBLE DEFAULT NULL ,
mean_chroma_cens_05 DOUBLE DEFAULT NULL ,
mean_chroma_cens_06 DOUBLE DEFAULT NULL ,
mean_chroma_cens_07 DOUBLE DEFAULT NULL ,
mean_chroma_cens_08 DOUBLE DEFAULT NULL ,
mean_chroma_cens_09 DOUBLE DEFAULT NULL ,
mean_chroma_cens_10 DOUBLE DEFAULT NULL ,
mean_chroma_cens_11 DOUBLE DEFAULT NULL ,
mean_chroma_cens_12 DOUBLE DEFAULT NULL ,
median_chroma_cens_01 DOUBLE DEFAULT NULL ,
median_chroma_cens_02 DOUBLE DEFAULT NULL ,
median_chroma_cens_03 DOUBLE DEFAULT NULL ,
median_chroma_cens_04 DOUBLE DEFAULT NULL ,
median_chroma_cens_05 DOUBLE DEFAULT NULL ,
median_chroma_cens_06 DOUBLE DEFAULT NULL ,
median_chroma_cens_07 DOUBLE DEFAULT NULL ,
median_chroma_cens_08 DOUBLE DEFAULT NULL ,
median_chroma_cens_09 DOUBLE DEFAULT NULL ,
median_chroma_cens_10 DOUBLE DEFAULT NULL ,
median_chroma_cens_11 DOUBLE DEFAULT NULL ,
median_chroma_cens_12 DOUBLE DEFAULT NULL ,
min_chroma_cens_01 DOUBLE DEFAULT NULL ,
min_chroma_cens_02 DOUBLE DEFAULT NULL ,
min_chroma_cens_03 DOUBLE DEFAULT NULL ,
min_chroma_cens_04 DOUBLE DEFAULT NULL ,
min_chroma_cens_05 DOUBLE DEFAULT NULL ,
min_chroma_cens_06 DOUBLE DEFAULT NULL ,
min_chroma_cens_07 DOUBLE DEFAULT NULL ,
min_chroma_cens_08 DOUBLE DEFAULT NULL ,
min_chroma_cens_09 DOUBLE DEFAULT NULL ,
min_chroma_cens_10 DOUBLE DEFAULT NULL ,
min_chroma_cens_11 DOUBLE DEFAULT NULL ,
min_chroma_cens_12 DOUBLE DEFAULT NULL ,
skew_chroma_cens_01 DOUBLE DEFAULT NULL ,
skew_chroma_cens_02 DOUBLE DEFAULT NULL ,
skew_chroma_cens_03 DOUBLE DEFAULT NULL ,
skew_chroma_cens_04 DOUBLE DEFAULT NULL ,
skew_chroma_cens_05 DOUBLE DEFAULT NULL ,
skew_chroma_cens_06 DOUBLE DEFAULT NULL ,
skew_chroma_cens_07 DOUBLE DEFAULT NULL ,
skew_chroma_cens_08 DOUBLE DEFAULT NULL ,
skew_chroma_cens_09 DOUBLE DEFAULT NULL ,
skew_chroma_cens_10 DOUBLE DEFAULT NULL ,
skew_chroma_cens_11 DOUBLE DEFAULT NULL ,
skew_chroma_cens_12 DOUBLE DEFAULT NULL ,
std_chroma_cens_01 DOUBLE DEFAULT NULL ,
std_chroma_cens_02 DOUBLE DEFAULT NULL ,
std_chroma_cens_03 DOUBLE DEFAULT NULL ,
std_chroma_cens_04 DOUBLE DEFAULT NULL ,
std_chroma_cens_05 DOUBLE DEFAULT NULL ,
std_chroma_cens_06 DOUBLE DEFAULT NULL ,
std_chroma_cens_07 DOUBLE DEFAULT NULL ,
std_chroma_cens_08 DOUBLE DEFAULT NULL ,
std_chroma_cens_09 DOUBLE DEFAULT NULL ,
std_chroma_cens_10 DOUBLE DEFAULT NULL ,
std_chroma_cens_11 DOUBLE DEFAULT NULL ,
std_chroma_cens_12 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_01 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_02 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_03 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_04 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_05 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_06 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_07 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_08 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_09 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_10 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_11 DOUBLE DEFAULT NULL ,
mean_chroma_cqt_12 DOUBLE DEFAULT NULL ,
median_chroma_cqt_01 DOUBLE DEFAULT NULL ,
median_chroma_cqt_02 DOUBLE DEFAULT NULL ,
median_chroma_cqt_03 DOUBLE DEFAULT NULL ,
median_chroma_cqt_04 DOUBLE DEFAULT NULL ,
median_chroma_cqt_05 DOUBLE DEFAULT NULL ,
median_chroma_cqt_06 DOUBLE DEFAULT NULL ,
median_chroma_cqt_07 DOUBLE DEFAULT NULL ,
median_chroma_cqt_08 DOUBLE DEFAULT NULL ,
median_chroma_cqt_09 DOUBLE DEFAULT NULL ,
median_chroma_cqt_10 DOUBLE DEFAULT NULL ,
median_chroma_cqt_11 DOUBLE DEFAULT NULL ,
median_chroma_cqt_12 DOUBLE DEFAULT NULL ,
min_chroma_cqt_01 DOUBLE DEFAULT NULL ,
min_chroma_cqt_02 DOUBLE DEFAULT NULL ,
min_chroma_cqt_03 DOUBLE DEFAULT NULL ,
min_chroma_cqt_04 DOUBLE DEFAULT NULL ,
min_chroma_cqt_05 DOUBLE DEFAULT NULL ,
min_chroma_cqt_06 DOUBLE DEFAULT NULL ,
min_chroma_cqt_07 DOUBLE DEFAULT NULL ,
min_chroma_cqt_08 DOUBLE DEFAULT NULL ,
min_chroma_cqt_09 DOUBLE DEFAULT NULL ,
min_chroma_cqt_10 DOUBLE DEFAULT NULL ,
min_chroma_cqt_11 DOUBLE DEFAULT NULL ,
min_chroma_cqt_12 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_03 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_04 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_05 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_06 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_07 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_08 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_09 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_10 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_11 DOUBLE DEFAULT NULL ,
skew_chroma_cqt_12 DOUBLE DEFAULT NULL ,
std_chroma_cqt_01 DOUBLE DEFAULT NULL ,
std_chroma_cqt_02 DOUBLE DEFAULT NULL ,
std_chroma_cqt_03 DOUBLE DEFAULT NULL ,
std_chroma_cqt_04 DOUBLE DEFAULT NULL ,
std_chroma_cqt_05 DOUBLE DEFAULT NULL ,
std_chroma_cqt_06 DOUBLE DEFAULT NULL ,
std_chroma_cqt_07 DOUBLE DEFAULT NULL ,
std_chroma_cqt_08 DOUBLE DEFAULT NULL ,
std_chroma_cqt_09 DOUBLE DEFAULT NULL ,
std_chroma_cqt_10 DOUBLE DEFAULT NULL ,
std_chroma_cqt_11 DOUBLE DEFAULT NULL ,
std_chroma_cqt_12 DOUBLE DEFAULT NULL ,
mean_chroma_stft_01 DOUBLE DEFAULT NULL ,
mean_chroma_stft_02 DOUBLE DEFAULT NULL ,
mean_chroma_stft_03 DOUBLE DEFAULT NULL ,
mean_chroma_stft_04 DOUBLE DEFAULT NULL ,
mean_chroma_stft_05 DOUBLE DEFAULT NULL ,
mean_chroma_stft_06 DOUBLE DEFAULT NULL ,
mean_chroma_stft_07 DOUBLE DEFAULT NULL ,
mean_chroma_stft_08 DOUBLE DEFAULT NULL ,
mean_chroma_stft_09 DOUBLE DEFAULT NULL ,
mean_chroma_stft_10 DOUBLE DEFAULT NULL ,
mean_chroma_stft_11 DOUBLE DEFAULT NULL ,
mean_chroma_stft_12 DOUBLE DEFAULT NULL ,
median_chroma_stft_01 DOUBLE DEFAULT NULL ,
median_chroma_stft_02 DOUBLE DEFAULT NULL ,
median_chroma_stft_03 DOUBLE DEFAULT NULL ,
median_chroma_stft_04 DOUBLE DEFAULT NULL ,
median_chroma_stft_05 DOUBLE DEFAULT NULL ,
median_chroma_stft_06 DOUBLE DEFAULT NULL ,
median_chroma_stft_07 DOUBLE DEFAULT NULL ,
median_chroma_stft_08 DOUBLE DEFAULT NULL ,
median_chroma_stft_09 DOUBLE DEFAULT NULL ,
median_chroma_stft_10 DOUBLE DEFAULT NULL ,
median_chroma_stft_11 DOUBLE DEFAULT NULL ,
median_chroma_stft_12 DOUBLE DEFAULT NULL ,
skew_chroma_stft_01 DOUBLE DEFAULT NULL ,
skew_chroma_stft_02 DOUBLE DEFAULT NULL ,
skew_chroma_stft_03 DOUBLE DEFAULT NULL ,
skew_chroma_stft_04 DOUBLE DEFAULT NULL ,
skew_chroma_stft_05 DOUBLE DEFAULT NULL ,
skew_chroma_stft_06 DOUBLE DEFAULT NULL ,
skew_chroma_stft_09 DOUBLE DEFAULT NULL ,
skew_chroma_stft_10 DOUBLE DEFAULT NULL ,
skew_chroma_stft_11 DOUBLE DEFAULT NULL ,
skew_chroma_stft_12 DOUBLE DEFAULT NULL ,
std_chroma_stft_01 DOUBLE DEFAULT NULL ,
std_chroma_stft_02 DOUBLE DEFAULT NULL ,
std_chroma_stft_03 DOUBLE DEFAULT NULL ,
std_chroma_stft_04 DOUBLE DEFAULT NULL ,
std_chroma_stft_05 DOUBLE DEFAULT NULL ,
std_chroma_stft_06 DOUBLE DEFAULT NULL ,
std_chroma_stft_07 DOUBLE DEFAULT NULL ,
std_chroma_stft_08 DOUBLE DEFAULT NULL ,
std_chroma_stft_09 DOUBLE DEFAULT NULL ,
std_chroma_stft_10 DOUBLE DEFAULT NULL ,
std_chroma_stft_11 DOUBLE DEFAULT NULL ,
std_chroma_stft_12 DOUBLE DEFAULT NULL ,
max_mfcc_01 DOUBLE DEFAULT NULL ,
max_mfcc_02 DOUBLE DEFAULT NULL ,
max_mfcc_03 DOUBLE DEFAULT NULL ,
max_mfcc_04 DOUBLE DEFAULT NULL ,
max_mfcc_05 DOUBLE DEFAULT NULL ,
max_mfcc_06 DOUBLE DEFAULT NULL ,
max_mfcc_07 DOUBLE DEFAULT NULL ,
max_mfcc_08 DOUBLE DEFAULT NULL ,
max_mfcc_09 DOUBLE DEFAULT NULL ,
max_mfcc_10 DOUBLE DEFAULT NULL ,
max_mfcc_11 DOUBLE DEFAULT NULL ,
max_mfcc_12 DOUBLE DEFAULT NULL ,
max_mfcc_13 DOUBLE DEFAULT NULL ,
max_mfcc_14 DOUBLE DEFAULT NULL ,
max_mfcc_15 DOUBLE DEFAULT NULL ,
max_mfcc_16 DOUBLE DEFAULT NULL ,
max_mfcc_17 DOUBLE DEFAULT NULL ,
max_mfcc_18 DOUBLE DEFAULT NULL ,
max_mfcc_19 DOUBLE DEFAULT NULL ,
max_mfcc_20 DOUBLE DEFAULT NULL ,
mean_mfcc_01 DOUBLE DEFAULT NULL ,
mean_mfcc_02 DOUBLE DEFAULT NULL ,
mean_mfcc_03 DOUBLE DEFAULT NULL ,
mean_mfcc_04 DOUBLE DEFAULT NULL ,
mean_mfcc_05 DOUBLE DEFAULT NULL ,
mean_mfcc_06 DOUBLE DEFAULT NULL ,
mean_mfcc_07 DOUBLE DEFAULT NULL ,
mean_mfcc_08 DOUBLE DEFAULT NULL ,
mean_mfcc_09 DOUBLE DEFAULT NULL ,
mean_mfcc_10 DOUBLE DEFAULT NULL ,
mean_mfcc_11 DOUBLE DEFAULT NULL ,
mean_mfcc_12 DOUBLE DEFAULT NULL ,
mean_mfcc_13 DOUBLE DEFAULT NULL ,
mean_mfcc_14 DOUBLE DEFAULT NULL ,
mean_mfcc_15 DOUBLE DEFAULT NULL ,
mean_mfcc_16 DOUBLE DEFAULT NULL ,
mean_mfcc_17 DOUBLE DEFAULT NULL ,
mean_mfcc_18 DOUBLE DEFAULT NULL ,
mean_mfcc_19 DOUBLE DEFAULT NULL ,
mean_mfcc_20 DOUBLE DEFAULT NULL ,
median_mfcc_01 DOUBLE DEFAULT NULL ,
median_mfcc_02 DOUBLE DEFAULT NULL ,
median_mfcc_03 DOUBLE DEFAULT NULL ,
median_mfcc_04 DOUBLE DEFAULT NULL ,
median_mfcc_05 DOUBLE DEFAULT NULL ,
median_mfcc_06 DOUBLE DEFAULT NULL ,
median_mfcc_07 DOUBLE DEFAULT NULL ,
median_mfcc_08 DOUBLE DEFAULT NULL ,
median_mfcc_09 DOUBLE DEFAULT NULL ,
median_mfcc_10 DOUBLE DEFAULT NULL ,
median_mfcc_11 DOUBLE DEFAULT NULL ,
median_mfcc_12 DOUBLE DEFAULT NULL ,
median_mfcc_13 DOUBLE DEFAULT NULL ,
median_mfcc_14 DOUBLE DEFAULT NULL ,
median_mfcc_15 DOUBLE DEFAULT NULL ,
median_mfcc_16 DOUBLE DEFAULT NULL ,
median_mfcc_17 DOUBLE DEFAULT NULL ,
median_mfcc_18 DOUBLE DEFAULT NULL ,
median_mfcc_19 DOUBLE DEFAULT NULL ,
median_mfcc_20 DOUBLE DEFAULT NULL ,
min_mfcc_03 DOUBLE DEFAULT NULL ,
min_mfcc_04 DOUBLE DEFAULT NULL ,
min_mfcc_05 DOUBLE DEFAULT NULL ,
min_mfcc_06 DOUBLE DEFAULT NULL ,
min_mfcc_07 DOUBLE DEFAULT NULL ,
min_mfcc_08 DOUBLE DEFAULT NULL ,
min_mfcc_09 DOUBLE DEFAULT NULL ,
min_mfcc_10 DOUBLE DEFAULT NULL ,
min_mfcc_11 DOUBLE DEFAULT NULL ,
min_mfcc_12 DOUBLE DEFAULT NULL ,
min_mfcc_13 DOUBLE DEFAULT NULL ,
min_mfcc_14 DOUBLE DEFAULT NULL ,
min_mfcc_15 DOUBLE DEFAULT NULL ,
min_mfcc_16 DOUBLE DEFAULT NULL ,
min_mfcc_17 DOUBLE DEFAULT NULL ,
min_mfcc_18 DOUBLE DEFAULT NULL ,
min_mfcc_19 DOUBLE DEFAULT NULL ,
min_mfcc_20 DOUBLE DEFAULT NULL ,
skew_mfcc_01 DOUBLE DEFAULT NULL ,
skew_mfcc_02 DOUBLE DEFAULT NULL ,
skew_mfcc_03 DOUBLE DEFAULT NULL ,
skew_mfcc_04 DOUBLE DEFAULT NULL ,
skew_mfcc_05 DOUBLE DEFAULT NULL ,
skew_mfcc_06 DOUBLE DEFAULT NULL ,
skew_mfcc_07 DOUBLE DEFAULT NULL ,
skew_mfcc_08 DOUBLE DEFAULT NULL ,
skew_mfcc_09 DOUBLE DEFAULT NULL ,
skew_mfcc_10 DOUBLE DEFAULT NULL ,
skew_mfcc_11 DOUBLE DEFAULT NULL ,
skew_mfcc_12 DOUBLE DEFAULT NULL ,
skew_mfcc_13 DOUBLE DEFAULT NULL ,
skew_mfcc_14 DOUBLE DEFAULT NULL ,
skew_mfcc_15 DOUBLE DEFAULT NULL ,
skew_mfcc_16 DOUBLE DEFAULT NULL ,
skew_mfcc_17 DOUBLE DEFAULT NULL ,
skew_mfcc_18 DOUBLE DEFAULT NULL ,
skew_mfcc_19 DOUBLE DEFAULT NULL ,
skew_mfcc_20 DOUBLE DEFAULT NULL ,
std_mfcc_01 DOUBLE DEFAULT NULL ,
std_mfcc_02 DOUBLE DEFAULT NULL ,
std_mfcc_03 DOUBLE DEFAULT NULL ,
std_mfcc_04 DOUBLE DEFAULT NULL ,
std_mfcc_05 DOUBLE DEFAULT NULL ,
std_mfcc_06 DOUBLE DEFAULT NULL ,
std_mfcc_07 DOUBLE DEFAULT NULL ,
std_mfcc_08 DOUBLE DEFAULT NULL ,
std_mfcc_09 DOUBLE DEFAULT NULL ,
std_mfcc_10 DOUBLE DEFAULT NULL ,
std_mfcc_11 DOUBLE DEFAULT NULL ,
std_mfcc_12 DOUBLE DEFAULT NULL ,
std_mfcc_13 DOUBLE DEFAULT NULL ,
std_mfcc_14 DOUBLE DEFAULT NULL ,
std_mfcc_15 DOUBLE DEFAULT NULL ,
std_mfcc_16 DOUBLE DEFAULT NULL ,
std_mfcc_17 DOUBLE DEFAULT NULL ,
std_mfcc_18 DOUBLE DEFAULT NULL ,
std_mfcc_19 DOUBLE DEFAULT NULL ,
std_mfcc_20 DOUBLE DEFAULT NULL ,
max_rmse_01 DOUBLE DEFAULT NULL ,
mean_rmse_01 DOUBLE DEFAULT NULL ,
median_rmse_01 DOUBLE DEFAULT NULL ,
skew_rmse_01 DOUBLE DEFAULT NULL ,
std_rmse_01 DOUBLE DEFAULT NULL ,
max_spectral_bandwidth_01 DOUBLE DEFAULT NULL ,
mean_spectral_bandwidth_01 DOUBLE DEFAULT NULL ,
median_spectral_bandwidth_01 DOUBLE DEFAULT NULL ,
min_spectral_bandwidth_01 DOUBLE DEFAULT NULL ,
skew_spectral_bandwidth_01 DOUBLE DEFAULT NULL ,
std_spectral_bandwidth_01 DOUBLE DEFAULT NULL ,
max_spectral_centroid_01 DOUBLE DEFAULT NULL ,
mean_spectral_centroid_01 DOUBLE DEFAULT NULL ,
median_spectral_centroid_01 DOUBLE DEFAULT NULL ,
min_spectral_centroid_01 DOUBLE DEFAULT NULL ,
skew_spectral_centroid_01 DOUBLE DEFAULT NULL ,
std_spectral_centroid_01 DOUBLE DEFAULT NULL ,
max_spectral_contrast_01 DOUBLE DEFAULT NULL ,
max_spectral_contrast_02 DOUBLE DEFAULT NULL ,
max_spectral_contrast_03 DOUBLE DEFAULT NULL ,
max_spectral_contrast_04 DOUBLE DEFAULT NULL ,
max_spectral_contrast_05 DOUBLE DEFAULT NULL ,
max_spectral_contrast_06 DOUBLE DEFAULT NULL ,
max_spectral_contrast_07 DOUBLE DEFAULT NULL ,
mean_spectral_contrast_01 DOUBLE DEFAULT NULL ,
mean_spectral_contrast_02 DOUBLE DEFAULT NULL ,
mean_spectral_contrast_03 DOUBLE DEFAULT NULL ,
mean_spectral_contrast_04 DOUBLE DEFAULT NULL ,
mean_spectral_contrast_05 DOUBLE DEFAULT NULL ,
mean_spectral_contrast_06 DOUBLE DEFAULT NULL ,
mean_spectral_contrast_07 DOUBLE DEFAULT NULL ,
median_spectral_contrast_01 DOUBLE DEFAULT NULL ,
median_spectral_contrast_02 DOUBLE DEFAULT NULL ,
median_spectral_contrast_03 DOUBLE DEFAULT NULL ,
median_spectral_contrast_04 DOUBLE DEFAULT NULL ,
median_spectral_contrast_05 DOUBLE DEFAULT NULL ,
median_spectral_contrast_06 DOUBLE DEFAULT NULL ,
median_spectral_contrast_07 DOUBLE DEFAULT NULL ,
min_spectral_contrast_01 DOUBLE DEFAULT NULL ,
min_spectral_contrast_02 DOUBLE DEFAULT NULL ,
min_spectral_contrast_03 DOUBLE DEFAULT NULL ,
min_spectral_contrast_04 DOUBLE DEFAULT NULL ,
min_spectral_contrast_05 DOUBLE DEFAULT NULL ,
min_spectral_contrast_06 DOUBLE DEFAULT NULL ,
min_spectral_contrast_07 DOUBLE DEFAULT NULL ,
skew_spectral_contrast_01 DOUBLE DEFAULT NULL ,
skew_spectral_contrast_02 DOUBLE DEFAULT NULL ,
skew_spectral_contrast_03 DOUBLE DEFAULT NULL ,
skew_spectral_contrast_04 DOUBLE DEFAULT NULL ,
skew_spectral_contrast_05 DOUBLE DEFAULT NULL ,
skew_spectral_contrast_06 DOUBLE DEFAULT NULL ,
skew_spectral_contrast_07 DOUBLE DEFAULT NULL ,
std_spectral_contrast_01 DOUBLE DEFAULT NULL ,
std_spectral_contrast_02 DOUBLE DEFAULT NULL ,
std_spectral_contrast_03 DOUBLE DEFAULT NULL ,
std_spectral_contrast_04 DOUBLE DEFAULT NULL ,
std_spectral_contrast_05 DOUBLE DEFAULT NULL ,
std_spectral_contrast_06 DOUBLE DEFAULT NULL ,
std_spectral_contrast_07 DOUBLE DEFAULT NULL ,
max_spectral_rolloff_01 DOUBLE DEFAULT NULL ,
mean_spectral_rolloff_01 DOUBLE DEFAULT NULL ,
median_spectral_rolloff_01 DOUBLE DEFAULT NULL ,
min_spectral_rolloff_01 DOUBLE DEFAULT NULL ,
skew_spectral_rolloff_01 DOUBLE DEFAULT NULL ,
std_spectral_rolloff_01 DOUBLE DEFAULT NULL ,
max_tonnetz_01 DOUBLE DEFAULT NULL ,
max_tonnetz_02 DOUBLE DEFAULT NULL ,
max_tonnetz_03 DOUBLE DEFAULT NULL ,
max_tonnetz_04 DOUBLE DEFAULT NULL ,
max_tonnetz_05 DOUBLE DEFAULT NULL ,
max_tonnetz_06 DOUBLE DEFAULT NULL ,
mean_tonnetz_01 DOUBLE DEFAULT NULL ,
mean_tonnetz_02 DOUBLE DEFAULT NULL ,
mean_tonnetz_03 DOUBLE DEFAULT NULL ,
mean_tonnetz_04 DOUBLE DEFAULT NULL ,
mean_tonnetz_05 DOUBLE DEFAULT NULL ,
mean_tonnetz_06 DOUBLE DEFAULT NULL ,
median_tonnetz_01 DOUBLE DEFAULT NULL ,
median_tonnetz_02 DOUBLE DEFAULT NULL ,
median_tonnetz_03 DOUBLE DEFAULT NULL ,
median_tonnetz_04 DOUBLE DEFAULT NULL ,
median_tonnetz_05 DOUBLE DEFAULT NULL ,
median_tonnetz_06 DOUBLE DEFAULT NULL ,
min_tonnetz_01 DOUBLE DEFAULT NULL ,
min_tonnetz_02 DOUBLE DEFAULT NULL ,
min_tonnetz_03 DOUBLE DEFAULT NULL ,
min_tonnetz_04 DOUBLE DEFAULT NULL ,
min_tonnetz_05 DOUBLE DEFAULT NULL ,
min_tonnetz_06 DOUBLE DEFAULT NULL ,
skew_tonnetz_01 DOUBLE DEFAULT NULL ,
skew_tonnetz_02 DOUBLE DEFAULT NULL ,
skew_tonnetz_03 DOUBLE DEFAULT NULL ,
skew_tonnetz_04 DOUBLE DEFAULT NULL ,
skew_tonnetz_05 DOUBLE DEFAULT NULL ,
skew_tonnetz_06 DOUBLE DEFAULT NULL ,
std_tonnetz_01 DOUBLE DEFAULT NULL ,
std_tonnetz_02 DOUBLE DEFAULT NULL ,
std_tonnetz_03 DOUBLE DEFAULT NULL ,
std_tonnetz_04 DOUBLE DEFAULT NULL ,
std_tonnetz_05 DOUBLE DEFAULT NULL ,
std_tonnetz_06 DOUBLE DEFAULT NULL ,
max_zcr_01 DOUBLE DEFAULT NULL ,
skew_zcr_01 DOUBLE DEFAULT NULL ,
std_zcr_01 DOUBLE DEFAULT NULL ,
);LOAD DATA LOCAL INFILE 'features.csv' INTO TABLE fullTable FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' IGNORE 4 LINES (trackID ,@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
max_chroma_cens_01 ,
max_chroma_cens_02 ,
max_chroma_cens_03 ,
max_chroma_cens_04 ,
max_chroma_cens_05 ,
max_chroma_cens_06 ,
max_chroma_cens_07 ,
max_chroma_cens_08 ,
max_chroma_cens_09 ,
max_chroma_cens_10 ,
max_chroma_cens_11 ,
max_chroma_cens_12 ,
mean_chroma_cens_01 ,
mean_chroma_cens_02 ,
mean_chroma_cens_03 ,
mean_chroma_cens_04 ,
mean_chroma_cens_05 ,
mean_chroma_cens_06 ,
mean_chroma_cens_07 ,
mean_chroma_cens_08 ,
mean_chroma_cens_09 ,
mean_chroma_cens_10 ,
mean_chroma_cens_11 ,
mean_chroma_cens_12 ,
median_chroma_cens_01 ,
median_chroma_cens_02 ,
median_chroma_cens_03 ,
median_chroma_cens_04 ,
median_chroma_cens_05 ,
median_chroma_cens_06 ,
median_chroma_cens_07 ,
median_chroma_cens_08 ,
median_chroma_cens_09 ,
median_chroma_cens_10 ,
median_chroma_cens_11 ,
median_chroma_cens_12 ,
min_chroma_cens_01 ,
min_chroma_cens_02 ,
min_chroma_cens_03 ,
min_chroma_cens_04 ,
min_chroma_cens_05 ,
min_chroma_cens_06 ,
min_chroma_cens_07 ,
min_chroma_cens_08 ,
min_chroma_cens_09 ,
min_chroma_cens_10 ,
min_chroma_cens_11 ,
min_chroma_cens_12 ,
skew_chroma_cens_01 ,
skew_chroma_cens_02 ,
skew_chroma_cens_03 ,
skew_chroma_cens_04 ,
skew_chroma_cens_05 ,
skew_chroma_cens_06 ,
skew_chroma_cens_07 ,
skew_chroma_cens_08 ,
skew_chroma_cens_09 ,
skew_chroma_cens_10 ,
skew_chroma_cens_11 ,
skew_chroma_cens_12 ,
std_chroma_cens_01 ,
std_chroma_cens_02 ,
std_chroma_cens_03 ,
std_chroma_cens_04 ,
std_chroma_cens_05 ,
std_chroma_cens_06 ,
std_chroma_cens_07 ,
std_chroma_cens_08 ,
std_chroma_cens_09 ,
std_chroma_cens_10 ,
std_chroma_cens_11 ,
std_chroma_cens_12 ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
mean_chroma_cqt_01 ,
mean_chroma_cqt_02 ,
mean_chroma_cqt_03 ,
mean_chroma_cqt_04 ,
mean_chroma_cqt_05 ,
mean_chroma_cqt_06 ,
mean_chroma_cqt_07 ,
mean_chroma_cqt_08 ,
mean_chroma_cqt_09 ,
mean_chroma_cqt_10 ,
mean_chroma_cqt_11 ,
mean_chroma_cqt_12 ,
median_chroma_cqt_01 ,
median_chroma_cqt_02 ,
median_chroma_cqt_03 ,
median_chroma_cqt_04 ,
median_chroma_cqt_05 ,
median_chroma_cqt_06 ,
median_chroma_cqt_07 ,
median_chroma_cqt_08 ,
median_chroma_cqt_09 ,
median_chroma_cqt_10 ,
median_chroma_cqt_11 ,
median_chroma_cqt_12 ,
min_chroma_cqt_01 ,
min_chroma_cqt_02 ,
min_chroma_cqt_03 ,
min_chroma_cqt_04 ,
min_chroma_cqt_05 ,
min_chroma_cqt_06 ,
min_chroma_cqt_07 ,
min_chroma_cqt_08 ,
min_chroma_cqt_09 ,
min_chroma_cqt_10 ,
min_chroma_cqt_11 ,
min_chroma_cqt_12 ,
@ignore ,
@ignore ,
skew_chroma_cqt_03 ,
skew_chroma_cqt_04 ,
skew_chroma_cqt_05 ,
skew_chroma_cqt_06 ,
skew_chroma_cqt_07 ,
skew_chroma_cqt_08 ,
skew_chroma_cqt_09 ,
skew_chroma_cqt_10 ,
skew_chroma_cqt_11 ,
skew_chroma_cqt_12 ,
std_chroma_cqt_01 ,
std_chroma_cqt_02 ,
std_chroma_cqt_03 ,
std_chroma_cqt_04 ,
std_chroma_cqt_05 ,
std_chroma_cqt_06 ,
std_chroma_cqt_07 ,
std_chroma_cqt_08 ,
std_chroma_cqt_09 ,
std_chroma_cqt_10 ,
std_chroma_cqt_11 ,
std_chroma_cqt_12 ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
mean_chroma_stft_01 ,
mean_chroma_stft_02 ,
mean_chroma_stft_03 ,
mean_chroma_stft_04 ,
mean_chroma_stft_05 ,
mean_chroma_stft_06 ,
mean_chroma_stft_07 ,
mean_chroma_stft_08 ,
mean_chroma_stft_09 ,
mean_chroma_stft_10 ,
mean_chroma_stft_11 ,
mean_chroma_stft_12 ,
median_chroma_stft_01 ,
median_chroma_stft_02 ,
median_chroma_stft_03 ,
median_chroma_stft_04 ,
median_chroma_stft_05 ,
median_chroma_stft_06 ,
median_chroma_stft_07 ,
median_chroma_stft_08 ,
median_chroma_stft_09 ,
median_chroma_stft_10 ,
median_chroma_stft_11 ,
median_chroma_stft_12 ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
skew_chroma_stft_01 ,
skew_chroma_stft_02 ,
skew_chroma_stft_03 ,
skew_chroma_stft_04 ,
skew_chroma_stft_05 ,
skew_chroma_stft_06 ,
@ignore ,
@ignore ,
skew_chroma_stft_09 ,
skew_chroma_stft_10 ,
skew_chroma_stft_11 ,
skew_chroma_stft_12 ,
std_chroma_stft_01 ,
std_chroma_stft_02 ,
std_chroma_stft_03 ,
std_chroma_stft_04 ,
std_chroma_stft_05 ,
std_chroma_stft_06 ,
std_chroma_stft_07 ,
std_chroma_stft_08 ,
std_chroma_stft_09 ,
std_chroma_stft_10 ,
std_chroma_stft_11 ,
std_chroma_stft_12 ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
max_mfcc_01 ,
max_mfcc_02 ,
max_mfcc_03 ,
max_mfcc_04 ,
max_mfcc_05 ,
max_mfcc_06 ,
max_mfcc_07 ,
max_mfcc_08 ,
max_mfcc_09 ,
max_mfcc_10 ,
max_mfcc_11 ,
max_mfcc_12 ,
max_mfcc_13 ,
max_mfcc_14 ,
max_mfcc_15 ,
max_mfcc_16 ,
max_mfcc_17 ,
max_mfcc_18 ,
max_mfcc_19 ,
max_mfcc_20 ,
mean_mfcc_01 ,
mean_mfcc_02 ,
mean_mfcc_03 ,
mean_mfcc_04 ,
mean_mfcc_05 ,
mean_mfcc_06 ,
mean_mfcc_07 ,
mean_mfcc_08 ,
mean_mfcc_09 ,
mean_mfcc_10 ,
mean_mfcc_11 ,
mean_mfcc_12 ,
mean_mfcc_13 ,
mean_mfcc_14 ,
mean_mfcc_15 ,
mean_mfcc_16 ,
mean_mfcc_17 ,
mean_mfcc_18 ,
mean_mfcc_19 ,
mean_mfcc_20 ,
median_mfcc_01 ,
median_mfcc_02 ,
median_mfcc_03 ,
median_mfcc_04 ,
median_mfcc_05 ,
median_mfcc_06 ,
median_mfcc_07 ,
median_mfcc_08 ,
median_mfcc_09 ,
median_mfcc_10 ,
median_mfcc_11 ,
median_mfcc_12 ,
median_mfcc_13 ,
median_mfcc_14 ,
median_mfcc_15 ,
median_mfcc_16 ,
median_mfcc_17 ,
median_mfcc_18 ,
median_mfcc_19 ,
median_mfcc_20 ,
@ignore ,
@ignore ,
min_mfcc_03 ,
min_mfcc_04 ,
min_mfcc_05 ,
min_mfcc_06 ,
min_mfcc_07 ,
min_mfcc_08 ,
min_mfcc_09 ,
min_mfcc_10 ,
min_mfcc_11 ,
min_mfcc_12 ,
min_mfcc_13 ,
min_mfcc_14 ,
min_mfcc_15 ,
min_mfcc_16 ,
min_mfcc_17 ,
min_mfcc_18 ,
min_mfcc_19 ,
min_mfcc_20 ,
skew_mfcc_01 ,
skew_mfcc_02 ,
skew_mfcc_03 ,
skew_mfcc_04 ,
skew_mfcc_05 ,
skew_mfcc_06 ,
skew_mfcc_07 ,
skew_mfcc_08 ,
skew_mfcc_09 ,
skew_mfcc_10 ,
skew_mfcc_11 ,
skew_mfcc_12 ,
skew_mfcc_13 ,
skew_mfcc_14 ,
skew_mfcc_15 ,
skew_mfcc_16 ,
skew_mfcc_17 ,
skew_mfcc_18 ,
skew_mfcc_19 ,
skew_mfcc_20 ,
std_mfcc_01 ,
std_mfcc_02 ,
std_mfcc_03 ,
std_mfcc_04 ,
std_mfcc_05 ,
std_mfcc_06 ,
std_mfcc_07 ,
std_mfcc_08 ,
std_mfcc_09 ,
std_mfcc_10 ,
std_mfcc_11 ,
std_mfcc_12 ,
std_mfcc_13 ,
std_mfcc_14 ,
std_mfcc_15 ,
std_mfcc_16 ,
std_mfcc_17 ,
std_mfcc_18 ,
std_mfcc_19 ,
std_mfcc_20 ,
@ignore ,
max_rmse_01 ,
mean_rmse_01 ,
median_rmse_01 ,
@ignore ,
skew_rmse_01 ,
std_rmse_01 ,
@ignore ,
max_spectral_bandwidth_01 ,
mean_spectral_bandwidth_01 ,
median_spectral_bandwidth_01 ,
min_spectral_bandwidth_01 ,
skew_spectral_bandwidth_01 ,
std_spectral_bandwidth_01 ,
@ignore ,
max_spectral_centroid_01 ,
mean_spectral_centroid_01 ,
median_spectral_centroid_01 ,
min_spectral_centroid_01 ,
skew_spectral_centroid_01 ,
std_spectral_centroid_01 ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
max_spectral_contrast_01 ,
max_spectral_contrast_02 ,
max_spectral_contrast_03 ,
max_spectral_contrast_04 ,
max_spectral_contrast_05 ,
max_spectral_contrast_06 ,
max_spectral_contrast_07 ,
mean_spectral_contrast_01 ,
mean_spectral_contrast_02 ,
mean_spectral_contrast_03 ,
mean_spectral_contrast_04 ,
mean_spectral_contrast_05 ,
mean_spectral_contrast_06 ,
mean_spectral_contrast_07 ,
median_spectral_contrast_01 ,
median_spectral_contrast_02 ,
median_spectral_contrast_03 ,
median_spectral_contrast_04 ,
median_spectral_contrast_05 ,
median_spectral_contrast_06 ,
median_spectral_contrast_07 ,
min_spectral_contrast_01 ,
min_spectral_contrast_02 ,
min_spectral_contrast_03 ,
min_spectral_contrast_04 ,
min_spectral_contrast_05 ,
min_spectral_contrast_06 ,
min_spectral_contrast_07 ,
skew_spectral_contrast_01 ,
skew_spectral_contrast_02 ,
skew_spectral_contrast_03 ,
skew_spectral_contrast_04 ,
skew_spectral_contrast_05 ,
skew_spectral_contrast_06 ,
skew_spectral_contrast_07 ,
std_spectral_contrast_01 ,
std_spectral_contrast_02 ,
std_spectral_contrast_03 ,
std_spectral_contrast_04 ,
std_spectral_contrast_05 ,
std_spectral_contrast_06 ,
std_spectral_contrast_07 ,
@ignore ,
max_spectral_rolloff_01 ,
mean_spectral_rolloff_01 ,
median_spectral_rolloff_01 ,
min_spectral_rolloff_01 ,
skew_spectral_rolloff_01 ,
std_spectral_rolloff_01 ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
@ignore ,
max_tonnetz_01 ,
max_tonnetz_02 ,
max_tonnetz_03 ,
max_tonnetz_04 ,
max_tonnetz_05 ,
max_tonnetz_06 ,
mean_tonnetz_01 ,
mean_tonnetz_02 ,
mean_tonnetz_03 ,
mean_tonnetz_04 ,
mean_tonnetz_05 ,
mean_tonnetz_06 ,
median_tonnetz_01 ,
median_tonnetz_02 ,
median_tonnetz_03 ,
median_tonnetz_04 ,
median_tonnetz_05 ,
median_tonnetz_06 ,
min_tonnetz_01 ,
min_tonnetz_02 ,
min_tonnetz_03 ,
min_tonnetz_04 ,
min_tonnetz_05 ,
min_tonnetz_06 ,
skew_tonnetz_01 ,
skew_tonnetz_02 ,
skew_tonnetz_03 ,
skew_tonnetz_04 ,
skew_tonnetz_05 ,
skew_tonnetz_06 ,
std_tonnetz_01 ,
std_tonnetz_02 ,
std_tonnetz_03 ,
std_tonnetz_04 ,
std_tonnetz_05 ,
std_tonnetz_06 ,
@ignore ,
max_zcr_01 ,
@ignore ,
@ignore ,
@ignore ,
skew_zcr_01 ,
std_zcr_01 ,
);